### ISSUE TITLE
Automatic Testing

### ISSUE THREAD

**Issue by arifjehoh** [kth-ii1302-vt22-group-3/web#35]
### SubTasks
- [x] Test URL
- [x] Test interactivety
- [x] Test Display view
- [ ] Test Graph view ( This is a issue as we can't really test a graph. Should we rely on just manual testing?

### Acceptance Criteria
- [ ] Passes DevOps for default values

https://stackoverflow.com/questions/43494739/snapshot-testing-chartjs-components-with-jest

**Comment by Gnormelli** [comment]
### SubTasks
- [ ] Test URL
- [ ] Test interactivety
- [ ] Test components x2

### Acceptance Criteria
- [ ] Passes DevOps for default values

**Comment by arifjehoh** [comment]
> ### SubTasks
> 
>     * [ ]  Test URL
> 
>     * [ ]  Test interactivety
> 
>     * [ ]  Test components x2
> 
> 
> ### Acceptance Criteria
> 
>     * [ ]  Passes DevOps for default values

Moved the comment to the start thread to get check box in the issue.
