### ISSUE TITLE
Implement Date-Time Picker

### ISSUE THREAD

**Issue by Gnormelli** [kth-ii1302-vt22-group-3/web#36]
### SubTasks
- [x] Choose free framework
- [x] Install framework on repo
- [x] Implement component 
- [x] Create default interval
- [x] Make component reactive to handle datasets filtration on website

### Acceptance Criteria
- [x] Graph shows picker with date/time intervall
