### ISSUE TITLE
Implement live rendering

### ISSUE THREAD

**Issue by arifjehoh** [kth-ii1302-vt22-group-3/web#38]
### SubTasks
- [ ] Implement interval fetch
- [ ] Observer rerenders implementation if changed 

### Acceptance Criteria
- [ ] Temperature component is updated automatically on  the website
